#!/usr/bin/env python3
"""Turn a steps.json storyline into a VHS .tape file (CLI demo path).

Usage:  python3 render_tape.py steps.json [project.json] > demo.tape

steps.json shape (see references/steps-schema.md):
{
  "type": "cli",
  "theme": "Catppuccin Mocha",   # optional camera styling (NOT the app UI)
  "font_size": 22,
  "width": 1200,
  "height": 640,
  "typing_speed_ms": 60,
  "output": {"gif": "demo.gif", "mp4": "demo.mp4"},
  "require": ["mytool"],          # binaries VHS should guard on
  "setup":   ["go build -o mytool . && export PATH=$PWD:$PATH", "clear"],
  "cleanup": ["rm -rf my-project"],
  "steps": [
    {"cmd": "mytool --help",        "wait": "Usage:",  "pause_ms": 1500},
    {"cmd": "mytool init my-proj",  "wait": "created", "pause_ms": 1500},
    {"cmd": "mytool run --fast",    "wait_line": "done", "pause_ms": 2500}
  ]
}

The generated tape runs the REAL commands (VHS types them into a real shell), so
captured output is genuine. setup/cleanup run off-camera inside Hide/Show.
"""
from __future__ import annotations

import json
import sys


def vhs_string(s: str) -> str:
    r"""Quote a string for a VHS `Type` command.

    VHS `Type "..."` types the string literally. We escape backslashes and
    double quotes. Commands containing chars VHS handles poorly ($, `, ") are
    still typed, but if you hit trouble, move the command into setup as a script.
    """
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(lines: list[str], steps: dict) -> None:
    add = lines.append

    # ---- Output targets ----
    out = steps.get("output") or {"gif": "demo.gif", "mp4": "demo.mp4"}
    for kind in ("mp4", "webm", "gif"):
        if out.get(kind):
            add(f"Output {out[kind]}")

    # ---- Dep guards ----
    for req in steps.get("require") or []:
        add(f"Require {req}")

    add("")

    # ---- Camera styling (outer frame only; never the app) ----
    add(f'Set Shell "{steps.get("shell", "bash")}"')
    add(f'Set FontSize {steps.get("font_size", 22)}')
    add(f'Set Width {steps.get("width", 1200)}')
    add(f'Set Height {steps.get("height", 640)}')
    if steps.get("theme"):
        add(f'Set Theme "{steps["theme"]}"')
    add(f'Set Padding {steps.get("padding", 20)}')
    add(f'Set TypingSpeed {steps.get("typing_speed_ms", 60)}ms')
    if steps.get("window_bar", True):
        add('Set WindowBar Colorful')
    add("")

    # ---- Off-camera setup ----
    setup = steps.get("setup") or []
    if setup:
        add("Hide")
        for cmd in setup:
            add(f"Type {vhs_string(cmd)}")
            add("Enter")
        add("Show")
        add("")

    # ---- Recorded steps: real commands, real output ----
    for i, step in enumerate(steps.get("steps") or []):
        cmd = step.get("cmd")
        if not cmd:
            continue
        add(f"# step {i + 1}")
        add(f"Type {vhs_string(cmd)}")
        add("Sleep 400ms")           # tiny beat before hitting enter — feels human
        add("Enter")
        if step.get("wait_line"):
            add(f"Wait+Line /{step['wait_line']}/")
        elif step.get("wait"):
            add(f"Wait /{step['wait']}/")
        add(f"Sleep {step.get('pause_ms', 1500)}ms")
        add("")

    # ---- Off-camera cleanup ----
    cleanup = steps.get("cleanup") or []
    if cleanup:
        add("Hide")
        for cmd in cleanup:
            add(f"Type {vhs_string(cmd)}")
            add("Enter")
        add("Show")


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: render_tape.py steps.json [project.json]", file=sys.stderr)
        return 2
    with open(sys.argv[1], encoding="utf-8") as fh:
        steps = json.load(fh)
    if steps.get("type") not in (None, "cli"):
        print(f"render_tape.py handles CLI demos; got type={steps.get('type')!r}",
              file=sys.stderr)
        return 2
    lines: list[str] = ["# demo.tape — generated by Vitrine"]
    emit(lines, steps)
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
